### ISSUE TITLE
Filter results by instance type or region (lists).

### ISSUE THREAD

**Issue by jcoleman0redhat0com** [AdiY10/SpotCalculator#2]
Feature request: allow the results to be filtered by instance type and region

For some workloads, only specific instance types or regions are required.  An example would be an application running on OSD, where only some instance types and regions are supported.  From https://docs.openshift.com/dedicated/osd_policy/osd-service-definition.html, the instance types must be M5, R5 or C5 and the supported regions (21) are also noted.

Note, that we can specify a specific region or "all" now, so it is possible to filter by region by running the optimiser multiple times and comparing the results, although this isn't ideal.

**Comment by AdiY10** [comment]
Hi Julian, Thanks for the issue.

1. TypeMajor feature has been added- you can specify which instance types can be selected:
* typeMajor - Used when specific instance types are required. For example, when only C5, R5, A1 are supported- insert "typeMajor": ["c5", "r5", "a1"]
2. In the region parameter you have few options:
* Region - used if a specific region is required, otherwise, searches in all regions.
  * region defined as "all"- to look for the best configuration, in all regions
  * region defined as specific region, for example "us-east-2"- to look for the best configuration only in us-east-2
  * region defined as list of multiple regions- ["eu-west-1","eu-east-2","sa-east-1"]- to look for the best configuration in these regions

last option suits your needs.

please, let me know if everything is clear, or something else is required
